apiVersion: v1
kind: Service
metadata:
  name: go-hello-microservice-service
spec:
  selector:
    app: go-hello-microservice
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 81
    targetPort: 8081
